Repository raunakkumarsingh/Cpp_Code, pull requests merged in 2022-10, with the labels that each got.

#27 Create maximizethevalue.cpp
  maximizethevalue.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#29 created a program to find minimum cost to reach last cell matrix.
  minimumcost.cpp
  subsetsumproblem.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#33 Solved Issue no #25
  Subset_Sum_Problem.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#31 LongestPalindromicSubsequence using dp
  LongestPalindromicSubsequence.cpp
Labels: hacktoberfest-accepted

#83 mergesort.cpp
  mergesort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#86 Added Selection Sort in Algorithm folder
  Algorithm/SelectionSort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#95 Create InsertionSort.cpp
  Algorithm/InsertionSort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#97 Code and Explanation of Boyer Moore Voting Algorithm
  Algorithm/Boyer_Moore_Majority_Voting_Algorithm.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#104 Bellman Ford Algorithm Added
  Algorithm/BellmanFordAlgorithm.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#112 Completed Floyd's Cycle Detection Algorithm and code
  Algorithm/floyd-detection-cycle-algorithm.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#111 Added Flood Fill Algorithm
  Algorithm/FloodFillAlgorithm.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#121 Added the new file for the Water Jug program in C++
  Water_Jug.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#120 added diff utility cpp code
  main.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#129 added the code for breadth first search in cpp
  Algorithm/Breadth_First_Search.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#132 added the solution code for 4 sum problem in cpp
  4_Sum_Problem.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#145 Create mergeSort.cpp
  Algorithm/mergeSort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#152 Create chess_knight.cpp
  chess_knight.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#153 3 partition problem
  3partition.cpp
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#154 box stack problem
  boxstack.cpp
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#156 Create k_Partition.cpp
  k_Partition.cpp
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#157 Create knight_tour.cpp
  knight_tour.cpp
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted
